JWT_SECRET = "chave_secreta_jwt"
usuario_master = "Master"
email_master = "bote_album11@icloud.com"
senha_master = "C4tatuia."
SENHA_EMAIL = "zdzf eweo jbri idjt"
EMAIL_REMETENTE = "sansquer@gmail.com"
EMAIL_SENHA = "zdzf eweo jbri idjt"
SMTP_SERVIDOR = "smtp.gmail.com"
SMTP_PORTA = 465