name: bf1
services:
  - name: web
    github:
      repo: sansquer77/BF1Dev
      branch: main
    build_command: pip install -r requirements.txt
    run_command: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
    http_port: 8501
    source_dir: 3.0
    health_check:
      http_path: /_stcore/health
    envs:
      - key: STREAMLIT_SERVER_MAXUPLOADSIZE
        value: "200"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_CLIENT_TOOLBARMODE
        value: "minimal"
      - key: STREAMLIT_LOGGER_LEVEL
        value: "info"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${JWT_SECRET}
      - key: EMAIL_REMETENTE
        scope: RUN_AND_BUILD_TIME
        value: ${EMAIL_REMETENTE}
      - key: SENHA_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: ${SENHA_EMAIL}
      - key: EMAIL_ADMIN
        scope: RUN_AND_BUILD_TIME
        value: ${EMAIL_ADMIN}
      - key: usuario_master
        scope: RUN_AND_BUILD_TIME
        value: ${usuario_master}
      - key: email_master
        scope: RUN_AND_BUILD_TIME
        value: ${email_master}
      - key: senha_master
        scope: RUN_AND_BUILD_TIME
        value: ${senha_master}
    
    # Volume para persistência do banco de dados
    volumes:
      - name: db-volume
        mount_path: /app/data
        filesystem_dir: data

volumes:
  - name: db-volume
    source_type: FILESYSTEM
    filesystem_config:
      size_gb: 1

static_sites: []
jobs: []
